name: Codespell

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Annotate locations with typos
        uses: codespell-project/codespell-problem-matcher@9ba2c57125d4908eade4308f32c4ff814c184633
      - name: Codespell
        uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
        with:
          check_hidden: true
          skip: .git